### PR TITLE
[Proposal] Privacy policy

### PR DESCRIPTION
**Pull request by Ilithy**
Proposal to add a privacy policy to Translate You.

_This is a preliminary proposal...it may require some adjustments on your part._

### CODE REVIEW

**Comment by Bnyro** [comment]
Hey, thanks for your work on that!
I wonder whether it wouldn't be a better idea to add a `Privacy` section directly to the README, otherwise many people would probably miss it.
Otherwise I could add a link to it into the app's About section :)

**Comment by Ilithy** [comment]
> Otherwise I could add a link to it into the app's About section

That's exactly what I thought

**Comment by Bnyro** [comment]
> I added a link in the Readme pointing to the privacy policy, does it look good to you? It's pretty basic, I know and It doesn't replace adding it in the app, but it's all I can do.
>
That's perfect, thank you <3
I'll add an icon for it on the bottom of the about section so nobody should miss it :O

**Comment by Ilithy** [comment]
>That's perfect, thank you <3

With pleasure

>I'll add an icon for it on the bottom of the about section so nobody should miss it

Its great but how about adding the privacy policy to the files to be translated? To make it more understandable, it would be directly stored and displayed in Translate You _(rather than a link to the file in github)_, in the user's language, without any intervention from the user _(i.e. having to translate it)_

**Comment by Bnyro** [comment]
> Its great but how about adding the privacy policy to the files to be translated? To make it more understandable, it would be directly stored and displayed in Translate You _(rather than a link to the file in github)_, in the user's language, without any intervention from the user _(i.e. having to translate it)_
>
Hmm, not sure about that since it'd be quite a lot of text to be translated. What I will do is show a dialog when the user clicks the icon in the about tab that fetches the Privacy Policy from GitHub and allows the user to copy it (after which they can paste it to translate it inside the app ;) ).
Benefits:
1. Not every translator has to translate such a long text.
2. When updating the Privacy Policy, the changes apply immediately inside the app and there's no need to update the app for it.
3. Adding it is fun for me :joy:
I hope you're okay with that, otherwise feel free to tell me your opinion ;)

**Comment by Ilithy** [comment]
It's a good compromise indeed and the points raised are correct, I have nothing to add 👍

**Pull request merged**
